In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
df = pd.read_csv('../data/train_v2.csv')

In [3]:
cv = CountVectorizer()
cv_matrix = cv.fit_transform(df.tags)
cv_df = pd.DataFrame(cv_matrix.toarray(),columns=cv.get_feature_names())

In [4]:
cv_df.head()

,agriculture,artisinal_mine,bare_ground,blooming,blow_down,clear,cloudy,conventional_mine,cultivation,habitation,haze,partly_cloudy,primary,road,selective_logging,slash_burn,water
0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0
1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
2,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,1,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0

In [5]:
# cv_df.to_csv('../data/count_vectorizer.csv',index=False)

In [8]:
co_matrix = np.matmul(cv_df.T.values,cv_df.values)
co_zero_diag = np.matmul(cv_df.T.values,cv_df.values)
np.fill_diagonal(co_zero_diag,0)

co_occurence = pd.DataFrame(co_matrix,
                           columns = cv_df.columns,
                           index=cv_df.columns)

co_zero = pd.DataFrame(co_zero_diag,
                      columns=cv_df.columns,
                      index=cv_df.columns)

In [10]:
co_zero

,agriculture,artisinal_mine,bare_ground,blooming,blow_down,clear,cloudy,conventional_mine,cultivation,habitation,haze,partly_cloudy,primary,road,selective_logging,slash_burn,water
agriculture,0,38,225,32,23,9150,0,24,3447,2737,672,2493,11972,6034,65,119,2712
artisinal_mine,38,0,40,0,0,307,0,4,18,29,5,27,324,110,6,0,299
bare_ground,225,40,0,3,4,747,0,10,89,163,41,74,683,323,13,10,206
blooming,32,0,3,0,1,311,0,0,35,4,4,17,332,10,7,2,16
blow_down,23,0,4,1,0,87,0,0,8,3,0,14,101,2,1,2,3
clear,9150,307,747,311,87,0,0,70,3583,3090,0,0,27668,6295,308,173,5502
cloudy,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
conventional_mine,24,4,10,0,0,70,0,0,4,36,2,28,94,59,0,0,26
cultivation,3447,18,89,35,8,3583,0,4,0,925,205,759,4523,1337,58,130,887
habitation,2737,29,163,4,3,3090,0,36,925,0,129,441,3469,2786,13,41,915
haze,672,5,41,4,0,0,0,2,205,129,0,0,2670,394,5,3,613
partly_cloudy,2493,27,74,17,14,0,0,28,759,441,0,0,7175,1382,27,33,1295
primary,11972,324,683,332,101,27668,0,94,4523,3469,2670,7175,0,7728,340,209,7001
road,6034,110,323,10,2,6295,0,59,1337,2786,394,1382,7728,0,151,36,2125
selective_logging,65,6,13,7,1,308,0,0,58,13,5,27,340,151,0,2,49
slash_burn,119,0,10,2,2,173,0,0,130,41,3,33,209,36,2,0,24
water,2712,299,206,16,3,5502,0,26,887,915,613,1295,7001,2125,49,24,0

In [12]:
# co_occurence.to_csv('../data/co_occurence.csv')
# co_zero.to_csv('../data/co_zero.csv')